name: CWEB CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: xu-cheng/texlive-action/full@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
