name: CWEB CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add build-base
          make
          make test
    - uses: actions/upload-artifact@v2
      with:
        name: sha256
        path: |
          sha256.pdf
          sha256.c
